### ISSUE TITLE
GR Suggestions

### ISSUE THREAD

**Issue by TheFloatingBrain** [tensorush/Awesome-Physics-Learning#1]
Cool repos! Wanted to throw in a couple of good YouTube channels for GR: 

 - [ScienceClic](https://www.youtube.com/watch?v=xodtfM1r9FA&list=PLu7cY2CPiRjVY-VaUZ69bXHZr5QslKbzo)
 - [dXoverdteqprogress (though he has some opinion pieces I don't agree with)](https://www.youtube.com/watch?v=BHKd6-IJgVI&list=PLbRB7u42hOE8rMIvShBxxiSdBdh9yQQL_)
 - [Eigen Chris](https://www.youtube.com/c/eigenchris)

Also some cool things are [Scott Manley's videos on Raytracing a Worm - Hole](https://www.youtube.com/watch?v=PVO8nvb1o2w), you can actually find the original code he uses in the link 

In addition [Code Parade](https://www.youtube.com/c/CodeParade) has some great videos on Game Development in non-euclidean spaces

[mtbdesignworks](https://www.youtube.com/c/mtbdesignworks) also has some great content on making a 4D game engine, these last few things may be better in your Awesome-Physics-Programming repo though

**Comment by tensorush** [comment]
Sweet! Thanks for expressing interest in my repos. Definitely adding these guys here. Code Parade a.k.a. [@HackerPoet](https://github.com/HackerPoet) is actually one of my favourite YouTubers + he's making what's going to become my favourite VR Game - [Hyperbolica](https://store.steampowered.com/app/1256230/Hyperbolica/). Speaking of that, I'm certainly adding his [Non-Euclidean Rendering Engine](https://github.com/HackerPoet/NonEuclidean) to the other repo. Thanks for pointing that out, too!

**Comment by TheFloatingBrain** [comment]
Awesome :smiley:
