### ISSUE TITLE
QM/Quantum Computing Suggestions

### ISSUE THREAD

**Issue by TheFloatingBrain** [tensorush/Awesome-Physics-Learning#2]
Just a couple of good introductory Quantum Computing/QM Resources 

 - [Quantum Computing for Computer Scientists](https://www.youtube.com/watch?v=F_Riqjdh2oM)
 - [AnastasiaMarchenkovaQuantum](https://www.youtube.com/c/AnastasiaMarchenkovaQuantum)

**Comment by tensorush** [comment]
Completely forgot about Quantum Computing and all the resources on this topic that I've been keeping in my bookmarks for some time now 😅 Thanks for reminding me! Already added them to [Awesome Physics Programming List](https://github.com/tensorush/Awesome-Physics-Programming#atom-quantum-computing).
