### ISSUE TITLE
One More Thing

### ISSUE THREAD

**Issue by TheFloatingBrain** [tensorush/Awesome-Physics-Learning#3]
Not to bombard you, this is a good course on [Numerical Relativity](https://www.youtube.com/watch?v=t3uo2R-yu4o&list=PL04QVxpjcnjh2mFtM-RsRmbcWhETPcasv)

**Comment by tensorush** [comment]
No, worries! Nice course and channel as well. I think I'll also be looking through the rest of that channel's playlists and adding some of them here. Thanks! That reminds me, I should finally get around to exploring at least some of MIT's great physics courses.
